### ISSUE TITLE
Sudo installs to the wrong path

### ISSUE THREAD

**Issue by kousu** [janhebnes/chocolatey-packages#2]
Hi! Thanks for your window-sudo package. I just discovered chocolatey and did `choco install git` and `choco install which` which both impressively worked, and even more impressively so did `choco install sudo`. However when I actually ran sudo I got:

```
C:\Users\john>sudo notepad
Cannot find file at '..\lib\sudo.1.0.1\bin\sudo.cmd' (C:\ProgramData\chocolatey\
lib\sudo.1.0.1\bin\sudo.cmd). This usually indicates a missing or moved file.
```

If I rename C:\ProgramData\chocolatey\lib\Sudo to C:\ProgramData\chocolatey\lib\sudo.1.0.1 then it works great, popping up UAC as expected. Maybe chocolatey changed something between the two years ago you wrote this (very elegant and clever!) shim and now.

**Comment by janhebnes** [comment]
This was resolved in the 1.0.2 release
