### ISSUE TITLE
sudo spawns new windows

### ISSUE THREAD

**Issue by kousu** [janhebnes/chocolatey-packages#3]
Hi again!

If I use your sudo with a command line program, say, `sudo git`, I get UAC and then just a cmd window flash by. Is there any way to get your sudo script to keep programs in the same command window?

**Comment by janhebnes** [comment]
It is using Shell.ShellExecute method from a vbs script to runas as a parameter. It can unfortunately not stay in the same window to my knowledge... even using tricks
