### ISSUE TITLE
Preserve current directory

### ISSUE THREAD

**Issue by KierranM** [janhebnes/chocolatey-packages#4]
Currently if I run `sudo notepad.exe ./somefile.txt` it will open notepad with the UAC prompt as expected, but notepad won't find the file because it looks for `C:\WINDOWS\System32\somefile.txt`. Is it possible to have the script preserve the working directory when it runs so that `.` and `..` work as expected.

**Comment by janhebnes** [comment]
Introduced in Sudo 1.1.0 with _sudo . notepad .\somefile.txt_
Can also be done using sudo notepad %cd%\somefile.txt

1.1.0 is in review.
