### ISSUE TITLE
Question: Is there an option to leave the sudo cmd window open?

### ISSUE THREAD

**Issue by urig** [janhebnes/chocolatey-packages#9]
Hi, and thanks for making `sudo`. I find it very useful, especially when I use chocolatey to install software.

I have a question, please. When I use `sudo` it opens a `cmd` window where the command is executed and once the command is complete, the window is closed. Is there a way to tell `sudo` to leave the window open until I "presss any key"?

Thanks,
@urig

**Comment by janhebnes** [comment]
Hi, adding "& pause" to the original command should leave the window open
with a prompt.

tor. 25. aug. 2022 21.18 skrev Uri Goldstein ***@***.***>:

**Comment by urig** [comment]
Thank you @janhebnes. Much appreciated. This works nicely in Command Prompt but does not work in PowerShell. Might you know how to do that? (I've tried getting it done based on answers in [this Stackoverflow question](https://stackoverflow.com/questions/9244280/how-to-get-powershell-to-keep-a-command-window-open) but did not succeed)
